apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  type: {{ .Values.payments.serviceType }}
  selector:
    app: payments
  ports:
    - name: http
      port: {{ .Values.payments.port }}
      targetPort: {{ .Values.payments.port }}
