apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  type: {{ .Values.reservations.serviceType }}
  selector:
    app: reservations
  ports:
    - name: http
      port: {{ .Values.reservations.port }}
      targetPort: {{ .Values.reservations.port }}
